### ISSUE TITLE
Invalid auth configuration

### ISSUE THREAD

**Issue by glonguetaud** [YunoHost-Apps/cypht_ynh#2] opened 2022-05-30 07:13 UTC
Hi, 
This is my first issue...

After installing the app, I can't acces to the admin page and I keep having this message when I log in the main one : 
`Invalid auth configuration` 

What did I miss ? 

Thank you !

**Comment by ericgaspar** [comment] 2022-06-05 06:05
I am not able to reproduce this issue...
are you using the credentials you set at install?

**Comment by glonguetaud** [comment] 2022-06-07 08:42
I don't have to enter any credential, whenever I go to https://my-domain/cypht (even in a private browser) I have the message mentioned above. 
Thanks for your help !

**Comment by marclaporte** [comment] 2024-05-21 15:18
@glonguetaud A lot has changed since your report 2 years ago. Can you please try again?

Thanks!

**Comment by glonguetaud** [comment] 2024-05-21 15:37
Hi @marclaporte unfortunately, I don't use cypht anymore… 
Thank you anyway !

**Comment by marclaporte** [comment] 2024-05-22 00:06
@glonguetaud If / when you come back, you will see a lot of improvements! https://github.com/cypht-org/cypht/releases

Soon Cypht 2.0.x is coming to YunoHost:
https://github.com/cypht-org/cypht/releases

@ericgaspar Please close this or provide me powers to do so.

Thanks!

**Closed as completed** 2024-05-22 06:21 UTC
